name: site_supervisor
description: Premium Construction Fleet Management App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  badges: ^3.0.2
  lottie: ^2.7.0          # Compatible with Flutter 3.32.7
  
  # Charts & Gauges
  syncfusion_flutter_gauges: ^23.2.7  # Compatible with Flutter 3.32.7
  fl_chart: ^0.61.0       # Compatible with vector_math 2.1.4
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Forms & Input
  flutter_form_builder: ^9.2.1   # Compatible with Dart 3.8.1
  
  # Navigation & Routing
  go_router: ^12.1.3      # Compatible with Flutter 3.32.7
  
  # Animations
  animations: ^2.0.7
  
  # Device Features
  image_picker: ^1.0.4
  camera: ^0.10.6         # Compatible with Dart 3.8.1
  permission_handler: ^11.4.0  # Compatible with Flutter 3.32.7
  url_launcher: ^6.1.11
  connectivity_plus: ^5.0.2    # Compatible version
  
  # Utilities
  intl: ^0.18.1           # Compatible version
  pull_to_refresh: ^2.0.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2   # Compatible with Flutter 3.32.7

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/animations/construction.json
  
  # Fonts


  # Generate files (if using code generation)
  generate: true