name: site_supervisor
description: Premium Construction Fleet Management App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_gauges: ^31.2.4
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI & Design
  flutter_svg: ^2.0.7
  lottie: ^3.3.2
  shimmer: ^3.0.0
  badges: ^3.0.2
  fl_chart: ^1.1.1
  
  # Forms & Input
  flutter_form_builder: ^10.2.0
  
  # Navigation & Routing
  go_router: ^16.3.0
  
  # Animations
  animations: ^2.0.7
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.1.11
  image_picker: ^1.0.4
  camera: ^0.11.3
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  pull_to_refresh: ^2.0.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/construction.json